apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    env: nginx
spec:
  type: NodePort
  selector:
    env: nginx
  ports:
    - port: 80         # Service port (ClusterIP port)
      targetPort: 80   # Container port (inside Pod)
      nodePort: 30001  # NodePort exposed externally