apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-pod
  name: redis-pod
spec:
  containers:
  - command:
    - redis-server
    - /redis-master/redis.conf
    image: redis:7
    name: redis-pod
    ports:
    - containerPort: 6379
    resources: {}
    volumeMounts:
    - mountPath: /redis-master
      name: redis-config
  volumes:
  - name: redis-config
    configMap:
      name: redis-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always