apiVersion: v1
kind: Pod
metadata:
  name: my-pod-cka
  labels:
    app: nginx
spec:
  containers:
  # Main nginx container
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-storage
      mountPath: /var/www/shared
      # Main container has read-write access (default)
  # Sidecar busybox container
  - name: sidecar
    image: busybox
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: shared-storage
      mountPath: /var/www/shared
      readOnly: true   # Sidecar has read‑only access
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: my-pvc-cka